### SPRING
spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: 'jdbc:h2:mem:library'
    username: 'user'
    password: ''
    driver-class-name: org.h2.Driver
  ### JPA
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none # dev : update
    properties:
      hibernate:
        globally_quoted_identifiers: true
        globally_quoted_identifiers_skip_column_definitions: true
        format_sql: true
        show_sql: true
  profiles:
    ### Verify (Vonage)
    include: vonage

server:
  port: 8080


---
